# step 1 build stage
FROM node:16.9-alpine3.13 AS build-stage
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
# Get build argument and set environment variable
# ARG URI
# ENV REACT_APP_URI=$URI
RUN npm run build

# step 2 production 
FROM nginx:1.19-alpine 
COPY --from=build-stage /app/build /usr/share/nginx/html
COPY ./default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]